In [1]:
import pandas as pd

In [17]:
data = [[1, 'john@example.com'], [2, 'bob@example.com'], [3, 'john@example.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'int64', 'email':'object'})

In [18]:
person

   id             email
0   1  john@example.com
1   2   bob@example.com
2   3  john@example.com

In [19]:
# safe move
person.sort_values(by="id", inplace=True)

In [20]:
person["duplicat"] = person["email"].duplicated()

In [21]:
person[person["duplicat"] == False].drop(columns=["duplicat"],axis=1)

   id             email
0   1  john@example.com
1   2   bob@example.com