In [1]:
import pandas as pd

In [2]:
data = [[1, '2015-01-01', 10], [2, '2015-01-02', 25], [3, '2015-01-03', 20], [4, '2015-01-04', 30]]
weather = pd.DataFrame(data, columns=['id', 'recordDate', 'temperature']).astype({'id':'Int64', 'recordDate':'datetime64[ns]', 'temperature':'Int64'})

In [20]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           4 non-null      Int64
 1   recordDate   4 non-null      datetime64[ns]
 2   temperature  4 non-null      Int64
dtypes: Int64(2), datetime64[ns](1)
memory usage: 232.0 bytes

In [25]:
weather.sort_values('recordDate', inplace=True)
weather

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

In [26]:
weather.temperature.diff()

0    <NA>
1      15
2      -5
3      10
Name: temperature, dtype: Int64

In [28]:
weather.recordDate.diff()

0      NaT
1   1 days
2   1 days
3   1 days
Name: recordDate, dtype: timedelta64[ns]

In [40]:
result = weather[(weather.recordDate.diff() == pd.Timedelta(days=1)) & (weather.temperature.diff() >= 0)]

In [39]:
result[["id"]]

   id
1   2
3   4