In [1]:
import pandas as pd

In [2]:
data = [[1, 1], [2, 2], [3, 3], [4, 3]]
orders = pd.DataFrame(data, columns=['order_number', 'customer_number']).astype({'order_number':'Int64', 'customer_number':'Int64'})

In [3]:
orders

   order_number  customer_number
0             1                1
1             2                2
2             3                3
3             4                3

In [27]:
orders = orders.groupby('customer_number')['order_number'].sum().reset_index()

In [30]:
orders.sort_values('order_number', ascending=False).head(1)

   customer_number  order_number
2                3             7