In [3]:
import pandas as pd

In [4]:
data = [['A', 'Math'], ['B', 'English'], ['C', 'Math'], ['D', 'Biology'], ['E', 'Math'], ['F', 'Computer'], ['G', 'Math'], ['H', 'Math'], ['I', 'Math']]
courses = pd.DataFrame(data, columns=['student', 'class']).astype({'student':'object', 'class':'object'})

In [22]:
courses
courses.groupby(["class"])["student"].nunique().reset_index()

      class  student
0   Biology        1
1  Computer        1
2   English        1
3      Math        6

In [20]:
result = courses.groupby('class').count().reset_index()
result

      class  student
0   Biology        1
1  Computer        1
2   English        1
3      Math        6

In [21]:
result[result['student'] >= 5][['class']]

  class
3  Math