In [66]:
import pandas as pd

data = [[1, 'a@b.com'], [2, 'c@d.com'], [3, 'a@b.com'], [4, 'a@b.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'Int64', 'email':'object'})
person

   id    email
0   1  a@b.com
1   2  c@d.com
2   3  a@b.com
3   4  a@b.com

In [ ]:


person["duplicat"] = person["email"].duplicated()
result = person[person["duplicat"] == True]
result.drop(columns=["duplicat"],axis=1).drop(columns=["id"],axis=1).rename(columns={"email":"Email"})

   id    email  duplicat
0   1  a@b.com     False
1   2  c@d.com     False
2   3  a@b.com      True

     Email
2  a@b.com

In [74]:
duplicate_rows = person.loc[person.duplicated('email') == True]
result = duplicate_rows[['email']].drop_duplicates()
result

     email
2  a@b.com

pandas.core.series.Series